FROM ruby:4.0.6-slim-bookworm

RUN apt-get update -qq && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    git \
    curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN gem install rails -v 8.1.3.1

COPY Gemfile Gemfile.lock ./
RUN bundle install

CMD ["bash"]