default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { "agendou" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "agendou9418" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: agendou_development

test:
  <<: *default
  database: agendou_test